[versions]
compose = "1.3.1"
composeCompiler = "1.3.2"
coreKtx = "1.10.1"
appcompat = "1.6.1"
material = "1.6.0"

[libraries]
compose = { module = "androidx.activity:activity-compose", version.ref = "compose" }
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }

[bundles]
baseViewFeature = ["coreKtx", "appcompat", "material"]